apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediawiki
spec:
  destination:
    namespace: jtudela-mediawiki
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.2.3
    chart: mediawiki
  project: default